### PR TITLE
Fix login notifications

### LINKED ISSUE #387: Display proper notification of login

### PR DESCRIPTION
**Pull request by yashwin**
fixes #387

### CODE REVIEW

File: config/environment.js [hunk 1]
```diff
@@ -190,7 +190,7 @@ module.exports = function(environment) {
     ENV['ember-cli-mirage'] = {
       enabled: false
     };
-    ENV['host'] = "http://localhost:8000";
+    ENV['host'] = "http://192.168.0.162:8000";
```
Comment (subho007) [inline config/environment.js]: @yashwin change it to `localhost`

File: app/components/login-component.coffee [hunk 2]
```diff
@@ -9,11 +9,9 @@ LoginComponentComponent = Ember.Component.extend
       identification = @get 'identification'
       password = @get 'password'
 
-      if !identification
-        that.get("notify").error "Please enter username or email address.", ENV.notifications
+      if !identification and !password
```
Comment (dhilipsiva) [inline app/components/login-component.coffee]: this should be `or`
